apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    env:
     - name: PGPASSWORD
       valueFrom:
         secretKeyRef:
            name: camunda.camunda-db.credentials
            key: password
    image: alpine
    stdin: true
    tty: true
