apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: camunda-db
  namespace: default
spec:
  teamId: "camunda"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    camunda:  # database owner
    - superuser
    - createdb
      #foo_user: []  # role for application foo
  databases:
    process_engine: camunda  # dbname: owner
    #preparedDatabases:
          # bar: {}
  postgresql:
    version: "12"
