---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-deployment
  labels:
    app: camunda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda-container
          image: soldann/camunda-docker:latest
          env:
            - name: DB_USERNAME
              value: camunda
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: camunda.camunda-db.credentials
                  key: password
            - name: DB_DRIVER
              value: org.postgresql.Driver
            - name: DB_URL
              value: jdbc:postgresql://camunda-db.default.svc.cluster.local/process_engine
            - name: WAIT_FOR
              value: camunda-db.default.svc.cluster.local:5432
            - name: WAIT_FOR_TIMEOUT
              value: "120"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: bpm-platform
              mountPath: /camunda/conf/bpm-platform.xml
      volumes:
        - name: bpm-platform
          hostPath: 
            path: /home/administrator/bpm-platform.xml
---
apiVersion: v1
kind: Service
metadata:
    name: camunda-service
spec:
    type: ClusterIP
    selector:
        app: camunda
    ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "28800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "28800"
spec:
  rules:
  - http:
      paths:
      - path: /camunda
        pathType: Prefix
        backend:
          serviceName: camunda-service
          servicePort: 8080
      - path: /camunda-welcome(/|$)
        pathType: Exact
        backend:
          serviceName: camunda-service
          servicePort: 8080
      - path: /engine-rest
        pathType: Prefix
        backend:
          serviceName: camunda-service
          servicePort: 8080
