---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-deployment
  labels:
    app: camunda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda-container
          image: soldann/camunda-docker:latest
          env:
            - name: DB_USERNAME
              value: zalando
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zalando.acid-minimal-cluster.credentials
                  key: password
            - name: DB_DRIVER
              value: org.postgresql.Driver
            - name: DB_URL
              value: jdbc:postgresql://acid-minimal-cluster.default.svc.cluster.local/postgres
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: camunda-service
spec:
    type: ClusterIP
    selector:
        app: camunda
    ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /app(/|$)(.*)
        backend:
          serviceName: camunda-service
          servicePort: 8080
