---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-deployment
  labels:
    app: camunda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda-container
          image: camunda/camunda-bpm-platform:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: camunda-service
spec:
    type: NodePort
    selector:
        app: camunda
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      name: http
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /app
        backend:
          serviceName: camunda-service
          servicePort: 8080
