---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manualk8s
provisioner: Local
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: manualk8s 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/camunda/"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-2
  labels:
    app: postgres
    type: local
spec:
  storageClassName: manualk8s
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/camunda2/"
